services:
  - type: web
    name: api-forense-backend
    env: python
    rootDir: ./backend            # <-- prefijo "./" para que Render lo reconozca sin dudas
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    disk:
      name: forense-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
